# ------------------------
# modal_steel_plate
# ------------------------
#
# None
#
#
# Author: None
# Description: None
# Date: 14/01/2025 11:14:08
# Generated by:
#   compas_fea2 v0.3.1
#   compas_fea2_opensees v0.2.0
#
#------------------------------------------------------------------
#------------------------------------------------------------------
# MODEL
#------------------------------------------------------------------
#------------------------------------------------------------------
#
##
# By default, models in compas_fea2 are defined in 3D.
model Basic -ndm 3
#
#==================================================================
# Materials
#==================================================================
#
uniaxialMaterial Elastic 0 210000.0
nDMaterial ElasticIsotropic 1000 210000.0 0.2 7.800000000000002e-09
#
#==================================================================
# Sections
#==================================================================
#

#
#==================================================================
# Parts
#==================================================================
#
#
#------------------------------------------------------------------
# Part OP_5386049376
#------------------------------------------------------------------
model Basic -ndm 3 -ndf 3
#
# Nodes
#------------------------------------------------------------------
#
#    tag        X       Y       Z       mx      my      mz
node 0      0.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 1    300.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 2    300.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 3      0.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 4      0.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 5    300.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 6      0.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 7    300.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 8    600.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 9    600.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 10    600.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 11    600.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 12    900.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 13    900.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 14    900.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 15    900.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 16   1200.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 17   1200.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 18   1200.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 19   1200.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 20   1500.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 21   1500.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 22   1500.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 23   1500.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 24   1800.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 25   1800.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 26   1800.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 27   1800.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 28   2100.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 29   2100.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 30   2100.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 31   2100.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 32   2400.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 33   2400.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 34   2400.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 35   2400.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 36   2700.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 37   2700.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 38   2700.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 39   2700.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 40   3000.00000000    333.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 41   3000.00000000      0.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 42   3000.00000000    666.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 43   3000.00000000   1000.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 44      0.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 45      0.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 46    300.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 47    300.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 48      0.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 49    300.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 50      0.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 51    300.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 52    600.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 53    600.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 54    600.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 55    600.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 56    900.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 57    900.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 58    900.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 59    900.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 60   1200.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 61   1200.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 62   1200.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 63   1200.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 64   1500.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 65   1500.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 66   1500.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 67   1500.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 68   1800.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 69   1800.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 70   1800.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 71   1800.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 72   2100.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 73   2100.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 74   2100.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 75   2100.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 76   2400.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 77   2400.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 78   2400.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 79   2400.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 80   2700.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 81   2700.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 82   2700.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 83   2700.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 84   3000.00000000    333.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 85   3000.00000000      0.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 86   3000.00000000    666.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 87   3000.00000000   1000.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 88    150.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 89    150.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 90    150.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 91    450.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 92    450.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 93    450.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 94    750.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 95    750.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 96    750.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 97   1050.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 98   1050.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 99   1050.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 100   1350.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 101   1350.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 102   1350.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 103   1650.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 104   1650.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 105   1650.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 106   1950.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 107   1950.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 108   1950.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 109   2250.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 110   2250.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 111   2250.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 112   2550.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 113   2550.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 114   2550.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 115   2850.00000000    166.66666667     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 116   2850.00000000    500.00000000     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 117   2850.00000000    833.33333333     -5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 118    150.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 119    150.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 120    150.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 121    450.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 122    450.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 123    450.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 124    750.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 125    750.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 126    750.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 127   1050.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 128   1050.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 129   1050.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 130   1350.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 131   1350.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 132   1350.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 133   1650.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 134   1650.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 135   1650.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 136   1950.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 137   1950.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 138   1950.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 139   2250.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 140   2250.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 141   2250.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 142   2550.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 143   2550.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 144   2550.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 145   2850.00000000    166.66666667      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 146   2850.00000000    500.00000000      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 147   2850.00000000    833.33333333      5.00000000 -mass      1.00000000      1.00000000      1.00000000
node 148    450.00000000     55.55555556     -0.00000000 -mass      1.00000000      1.00000000      1.00000000
node 149   1450.00000000    500.00000000     -0.00000000 -mass      1.00000000      1.00000000      1.00000000
node 150   1650.00000000     55.55555556     -0.00000000 -mass      1.00000000      1.00000000      1.00000000
node 151   2150.00000000    833.33333333     -0.00000000 -mass      1.00000000      1.00000000      1.00000000
node 152   1750.00000000    833.33333333      0.00000000 -mass      1.00000000      1.00000000      1.00000000
node 153   1950.00000000     55.55555556      0.00000000 -mass      1.00000000      1.00000000      1.00000000
node 154   2350.00000000    500.00000000     -0.00000000 -mass      1.00000000      1.00000000      1.00000000
#
# Elements
#------------------------------------------------------------------
#
element FourNodeTetrahedron 0 53 2 47 148 1000
element FourNodeTetrahedron 1 9 2 53 148 1000
element FourNodeTetrahedron 2 29 25 69 153 1000
element FourNodeTetrahedron 3 69 73 29 153 1000
element FourNodeTetrahedron 4 69 25 21 150 1000
element FourNodeTetrahedron 5 65 69 21 150 1000
element FourNodeTetrahedron 6 15 58 126 96 1000
element FourNodeTetrahedron 7 56 98 58 128 1000
element FourNodeTetrahedron 8 52 91 9 121 1000
element FourNodeTetrahedron 9 127 13 56 97 1000
element FourNodeTetrahedron 10 139 32 77 109 1000
element FourNodeTetrahedron 11 120 51 5 90 1000
element FourNodeTetrahedron 12 12 125 58 95 1000
element FourNodeTetrahedron 13 51 5 93 123 1000
element FourNodeTetrahedron 14 74 107 28 137 1000
element FourNodeTetrahedron 15 136 25 68 106 1000
element FourNodeTetrahedron 16 37 145 115 36 1000
element FourNodeTetrahedron 17 86 116 40 146 1000
element FourNodeTetrahedron 18 91 9 121 148 1000
element FourNodeTetrahedron 19 25 133 103 150 1000
element FourNodeTetrahedron 20 136 25 106 153 1000
element FourNodeTetrahedron 21 106 73 136 153 1000
element FourNodeTetrahedron 22 65 103 133 150 1000
element FourNodeTetrahedron 23 47 91 121 148 1000
element FourNodeTetrahedron 24 111 74 141 151 1000
element FourNodeTetrahedron 25 135 70 105 152 1000
element FourNodeTetrahedron 26 34 140 110 154 1000
element FourNodeTetrahedron 27 14 15 58 99 1000
element FourNodeTetrahedron 28 15 14 58 96 1000
element FourNodeTetrahedron 29 58 15 126 59 1000
element FourNodeTetrahedron 30 51 49 5 123 1000
element FourNodeTetrahedron 31 19 18 62 99 1000
element FourNodeTetrahedron 32 49 51 5 120 1000
element FourNodeTetrahedron 33 35 34 78 111 1000
element FourNodeTetrahedron 34 51 5 90 7 1000
element FourNodeTetrahedron 35 91 52 9 8 1000
element FourNodeTetrahedron 36 13 127 56 57 1000
element FourNodeTetrahedron 37 38 39 82 117 1000
element FourNodeTetrahedron 38 39 38 82 114 1000
element FourNodeTetrahedron 39 32 139 77 76 1000
element FourNodeTetrahedron 40 34 35 78 114 1000
element FourNodeTetrahedron 41 28 74 110 30 1000
element FourNodeTetrahedron 42 12 125 56 58 1000
element FourNodeTetrahedron 43 94 56 13 12 1000
element FourNodeTetrahedron 44 12 56 13 97 1000
element FourNodeTetrahedron 45 98 56 58 12 1000
element FourNodeTetrahedron 46 8 52 9 94 1000
element FourNodeTetrahedron 47 9 52 121 53 1000
element FourNodeTetrahedron 48 72 74 28 137 1000
element FourNodeTetrahedron 49 69 68 25 133 1000
element FourNodeTetrahedron 50 37 145 36 81 1000
element FourNodeTetrahedron 51 36 37 81 112 1000
element FourNodeTetrahedron 52 68 70 24 134 1000
element FourNodeTetrahedron 53 32 33 77 109 1000
element FourNodeTetrahedron 54 25 24 68 106 1000
element FourNodeTetrahedron 55 21 20 65 103 1000
element FourNodeTetrahedron 56 81 36 80 145 1000
element FourNodeTetrahedron 57 33 32 77 112 1000
element FourNodeTetrahedron 58 14 12 58 95 1000
element FourNodeTetrahedron 59 20 21 65 100 1000
element FourNodeTetrahedron 60 10 8 52 92 1000
element FourNodeTetrahedron 61 68 69 25 136 1000
element FourNodeTetrahedron 62 70 107 24 26 1000
element FourNodeTetrahedron 63 14 12 98 58 1000
element FourNodeTetrahedron 64 74 107 30 28 1000
element FourNodeTetrahedron 65 18 19 62 102 1000
element FourNodeTetrahedron 66 51 5 7 93 1000
element FourNodeTetrahedron 67 10 52 125 54 1000
element FourNodeTetrahedron 68 84 145 41 85 1000
element FourNodeTetrahedron 69 116 86 40 42 1000
element FourNodeTetrahedron 70 6 120 50 48 1000
element FourNodeTetrahedron 71 43 86 117 42 1000
element FourNodeTetrahedron 72 118 45 0 44 1000
element FourNodeTetrahedron 73 89 4 0 45 1000
element FourNodeTetrahedron 74 86 40 84 146 1000
element FourNodeTetrahedron 75 138 108 30 26 1000
element FourNodeTetrahedron 76 123 10 5 93 1000
element FourNodeTetrahedron 77 28 32 139 109 1000
element FourNodeTetrahedron 78 20 104 134 24 1000
element FourNodeTetrahedron 79 60 98 56 128 1000
element FourNodeTetrahedron 80 107 74 70 137 1000
element FourNodeTetrahedron 81 58 10 95 125 1000
element FourNodeTetrahedron 82 96 15 55 126 1000
element FourNodeTetrahedron 83 34 140 74 110 1000
element FourNodeTetrahedron 84 13 17 97 127 1000
element FourNodeTetrahedron 85 94 52 124 56 1000
element FourNodeTetrahedron 86 81 77 142 112 1000
element FourNodeTetrahedron 87 22 18 101 131 1000
element FourNodeTetrahedron 88 62 99 58 129 1000
element FourNodeTetrahedron 89 78 111 74 141 1000
element FourNodeTetrahedron 90 82 114 78 144 1000
element FourNodeTetrahedron 91 102 132 62 66 1000
element FourNodeTetrahedron 92 27 135 23 105 1000
element FourNodeTetrahedron 93 118 0 1 88 1000
element FourNodeTetrahedron 94 46 119 89 45 1000
element FourNodeTetrahedron 95 120 6 51 90 1000
element FourNodeTetrahedron 96 41 145 115 37 1000
element FourNodeTetrahedron 97 146 82 86 116 1000
element FourNodeTetrahedron 98 147 86 82 117 1000
element FourNodeTetrahedron 99 121 9 53 148 1000
element FourNodeTetrahedron 100 25 69 133 150 1000
element FourNodeTetrahedron 101 69 25 136 153 1000
element FourNodeTetrahedron 102 73 106 29 153 1000
element FourNodeTetrahedron 103 65 21 103 150 1000
element FourNodeTetrahedron 104 2 91 47 148 1000
element FourNodeTetrahedron 105 91 8 1 52 1000
element FourNodeTetrahedron 106 98 58 18 14 1000
element FourNodeTetrahedron 107 93 51 11 7 1000
element FourNodeTetrahedron 108 95 14 10 58 1000
element FourNodeTetrahedron 109 125 58 10 54 1000
element FourNodeTetrahedron 110 65 17 100 21 1000
element FourNodeTetrahedron 111 135 23 67 27 1000
element FourNodeTetrahedron 112 76 139 72 28 1000
element FourNodeTetrahedron 113 139 76 32 28 1000
element FourNodeTetrahedron 114 109 77 29 33 1000
element FourNodeTetrahedron 115 85 145 37 81 1000
element FourNodeTetrahedron 116 15 11 96 55 1000
element FourNodeTetrahedron 117 1 8 92 52 1000
element FourNodeTetrahedron 118 61 13 127 17 1000
element FourNodeTetrahedron 119 72 68 137 28 1000
element FourNodeTetrahedron 120 24 28 68 106 1000
element FourNodeTetrahedron 121 141 75 79 31 1000
element FourNodeTetrahedron 122 80 76 143 36 1000
element FourNodeTetrahedron 123 110 32 76 28 1000
element FourNodeTetrahedron 124 81 33 112 37 1000
element FourNodeTetrahedron 125 33 81 112 77 1000
element FourNodeTetrahedron 126 61 13 57 127 1000
element FourNodeTetrahedron 127 10 14 96 58 1000
element FourNodeTetrahedron 128 58 99 18 14 1000
element FourNodeTetrahedron 129 59 55 15 126 1000
element FourNodeTetrahedron 130 74 78 140 34 1000
element FourNodeTetrahedron 131 78 113 34 38 1000
element FourNodeTetrahedron 132 67 71 135 27 1000
element FourNodeTetrahedron 133 30 111 74 34 1000
element FourNodeTetrahedron 134 18 22 62 131 1000
element FourNodeTetrahedron 135 66 62 22 131 1000
element FourNodeTetrahedron 136 99 62 58 18 1000
element FourNodeTetrahedron 137 82 114 38 78 1000
element FourNodeTetrahedron 138 34 114 78 38 1000
element FourNodeTetrahedron 139 111 78 74 34 1000
element FourNodeTetrahedron 140 74 30 34 110 1000
element FourNodeTetrahedron 141 18 22 102 62 1000
element FourNodeTetrahedron 142 62 22 102 66 1000
element FourNodeTetrahedron 143 70 22 105 26 1000
element FourNodeTetrahedron 144 1 45 118 46 1000
element FourNodeTetrahedron 145 41 145 37 85 1000
element FourNodeTetrahedron 146 46 89 1 45 1000
element FourNodeTetrahedron 147 6 120 51 50 1000
element FourNodeTetrahedron 148 7 6 90 51 1000
element FourNodeTetrahedron 149 49 120 5 48 1000
element FourNodeTetrahedron 150 0 118 1 45 1000
element FourNodeTetrahedron 151 89 0 1 45 1000
element FourNodeTetrahedron 152 22 66 131 149 1000
element FourNodeTetrahedron 153 103 21 25 150 1000
element FourNodeTetrahedron 154 133 69 65 150 1000
element FourNodeTetrahedron 155 66 64 131 149 1000
element FourNodeTetrahedron 156 53 47 121 148 1000
element FourNodeTetrahedron 157 141 75 31 151 1000
element FourNodeTetrahedron 158 71 70 135 152 1000
element FourNodeTetrahedron 159 71 135 27 152 1000
element FourNodeTetrahedron 160 141 31 111 151 1000
element FourNodeTetrahedron 161 140 76 110 154 1000
element FourNodeTetrahedron 162 29 106 25 153 1000
element FourNodeTetrahedron 163 9 91 2 148 1000
element FourNodeTetrahedron 164 27 135 105 152 1000
element FourNodeTetrahedron 165 141 74 75 151 1000
element FourNodeTetrahedron 166 110 32 34 154 1000
element FourNodeTetrahedron 167 101 22 131 149 1000
element FourNodeTetrahedron 168 32 110 76 154 1000
element FourNodeTetrahedron 169 73 69 136 153 1000
element FourNodeTetrahedron 170 20 65 133 64 1000
element FourNodeTetrahedron 171 133 65 20 103 1000
element FourNodeTetrahedron 172 76 142 36 80 1000
element FourNodeTetrahedron 173 81 36 142 80 1000
element FourNodeTetrahedron 174 81 142 36 112 1000
element FourNodeTetrahedron 175 79 144 39 83 1000
element FourNodeTetrahedron 176 82 39 144 83 1000
element FourNodeTetrahedron 177 82 144 39 114 1000
element FourNodeTetrahedron 178 39 144 35 114 1000
element FourNodeTetrahedron 179 39 35 144 79 1000
element FourNodeTetrahedron 180 78 35 144 114 1000
element FourNodeTetrahedron 181 78 144 35 79 1000
element FourNodeTetrahedron 182 63 15 129 59 1000
element FourNodeTetrahedron 183 58 15 129 99 1000
element FourNodeTetrahedron 184 58 129 15 59 1000
element FourNodeTetrahedron 185 57 124 9 53 1000
element FourNodeTetrahedron 186 52 9 124 53 1000
element FourNodeTetrahedron 187 52 124 9 94 1000
element FourNodeTetrahedron 188 87 39 147 83 1000
element FourNodeTetrahedron 189 82 39 147 117 1000
element FourNodeTetrahedron 190 82 147 39 83 1000
element FourNodeTetrahedron 191 67 19 132 63 1000
element FourNodeTetrahedron 192 62 19 132 102 1000
element FourNodeTetrahedron 193 62 132 19 63 1000
element FourNodeTetrahedron 194 5 10 122 92 1000
element FourNodeTetrahedron 195 52 10 122 54 1000
element FourNodeTetrahedron 196 52 122 10 92 1000
element FourNodeTetrahedron 197 28 137 24 68 1000
element FourNodeTetrahedron 198 28 24 137 107 1000
element FourNodeTetrahedron 199 70 24 137 68 1000
element FourNodeTetrahedron 200 70 137 24 107 1000
element FourNodeTetrahedron 201 31 141 35 79 1000
element FourNodeTetrahedron 202 31 35 141 111 1000
element FourNodeTetrahedron 203 78 35 141 79 1000
element FourNodeTetrahedron 204 78 141 35 111 1000
element FourNodeTetrahedron 205 76 140 28 72 1000
element FourNodeTetrahedron 206 76 28 140 110 1000
element FourNodeTetrahedron 207 74 28 140 72 1000
element FourNodeTetrahedron 208 74 140 28 110 1000
element FourNodeTetrahedron 209 24 104 70 26 1000
element FourNodeTetrahedron 210 24 70 104 134 1000
element FourNodeTetrahedron 211 22 70 104 26 1000
element FourNodeTetrahedron 212 2 44 88 3 1000
element FourNodeTetrahedron 213 0 44 88 118 1000
element FourNodeTetrahedron 214 0 88 44 3 1000
element FourNodeTetrahedron 215 147 86 43 87 1000
element FourNodeTetrahedron 216 43 86 147 117 1000
element FourNodeTetrahedron 217 43 39 147 87 1000
element FourNodeTetrahedron 218 147 39 43 117 1000
element FourNodeTetrahedron 219 5 90 48 120 1000
element FourNodeTetrahedron 220 5 48 90 4 1000
element FourNodeTetrahedron 221 6 48 90 120 1000
element FourNodeTetrahedron 222 6 90 48 4 1000
element FourNodeTetrahedron 223 62 19 129 63 1000
element FourNodeTetrahedron 224 62 129 19 99 1000
element FourNodeTetrahedron 225 15 129 19 63 1000
element FourNodeTetrahedron 226 15 19 129 99 1000
element FourNodeTetrahedron 227 36 32 142 76 1000
element FourNodeTetrahedron 228 36 142 32 112 1000
element FourNodeTetrahedron 229 77 142 32 76 1000
element FourNodeTetrahedron 230 77 32 142 112 1000
element FourNodeTetrahedron 231 9 13 124 57 1000
element FourNodeTetrahedron 232 9 124 13 94 1000
element FourNodeTetrahedron 233 56 124 13 57 1000
element FourNodeTetrahedron 234 56 13 124 94 1000
element FourNodeTetrahedron 235 62 60 18 131 1000
element FourNodeTetrahedron 236 16 60 18 98 1000
element FourNodeTetrahedron 237 11 55 10 96 1000
element FourNodeTetrahedron 238 54 55 10 123 1000
element FourNodeTetrahedron 239 10 93 55 11 1000
element FourNodeTetrahedron 240 10 55 93 123 1000
element FourNodeTetrahedron 241 51 55 93 11 1000
element FourNodeTetrahedron 242 51 93 55 123 1000
element FourNodeTetrahedron 243 2 1 47 91 1000
element FourNodeTetrahedron 244 46 1 47 118 1000
element FourNodeTetrahedron 245 47 121 1 46 1000
element FourNodeTetrahedron 246 47 1 121 91 1000
element FourNodeTetrahedron 247 52 1 121 46 1000
element FourNodeTetrahedron 248 52 121 1 91 1000
element FourNodeTetrahedron 249 29 73 28 106 1000
element FourNodeTetrahedron 250 72 73 28 139 1000
element FourNodeTetrahedron 251 34 154 78 140 1000
element FourNodeTetrahedron 252 76 78 154 140 1000
element FourNodeTetrahedron 253 149 22 20 101 1000
element FourNodeTetrahedron 254 17 16 60 100 1000
element FourNodeTetrahedron 255 17 61 60 127 1000
element FourNodeTetrahedron 256 58 128 18 62 1000
element FourNodeTetrahedron 257 58 18 128 98 1000
element FourNodeTetrahedron 258 60 18 128 62 1000
element FourNodeTetrahedron 259 60 128 18 98 1000
element FourNodeTetrahedron 260 80 82 36 143 1000
element FourNodeTetrahedron 261 38 82 36 116 1000
element FourNodeTetrahedron 262 68 136 28 72 1000
element FourNodeTetrahedron 263 68 28 136 106 1000
element FourNodeTetrahedron 264 73 28 136 72 1000
element FourNodeTetrahedron 265 73 136 28 106 1000
element FourNodeTetrahedron 266 18 101 60 16 1000
element FourNodeTetrahedron 267 18 60 101 131 1000
element FourNodeTetrahedron 268 23 22 66 102 1000
element FourNodeTetrahedron 269 23 67 66 135 1000
element FourNodeTetrahedron 270 30 31 151 111 1000
element FourNodeTetrahedron 271 151 74 30 111 1000
element FourNodeTetrahedron 272 49 46 5 122 1000
element FourNodeTetrahedron 273 1 46 5 89 1000
element FourNodeTetrahedron 274 26 70 152 105 1000
element FourNodeTetrahedron 275 152 27 26 105 1000
element FourNodeTetrahedron 276 55 126 10 96 1000
element FourNodeTetrahedron 277 55 10 126 54 1000
element FourNodeTetrahedron 278 58 10 126 96 1000
element FourNodeTetrahedron 279 58 126 10 54 1000
element FourNodeTetrahedron 280 23 105 66 22 1000
element FourNodeTetrahedron 281 23 66 105 135 1000
element FourNodeTetrahedron 282 70 66 105 22 1000
element FourNodeTetrahedron 283 70 105 66 135 1000
element FourNodeTetrahedron 284 46 119 5 89 1000
element FourNodeTetrahedron 285 46 5 119 49 1000
element FourNodeTetrahedron 286 48 119 5 49 1000
element FourNodeTetrahedron 287 146 40 36 116 1000
element FourNodeTetrahedron 288 36 82 146 116 1000
element FourNodeTetrahedron 289 146 82 36 80 1000
element FourNodeTetrahedron 290 68 134 20 64 1000
element FourNodeTetrahedron 291 20 134 68 24 1000
element FourNodeTetrahedron 292 20 133 68 64 1000
element FourNodeTetrahedron 293 5 46 92 122 1000
element FourNodeTetrahedron 294 5 92 46 1 1000
element FourNodeTetrahedron 295 52 92 46 122 1000
element FourNodeTetrahedron 296 52 46 92 1 1000
element FourNodeTetrahedron 297 65 17 130 100 1000
element FourNodeTetrahedron 298 65 130 17 61 1000
element FourNodeTetrahedron 299 60 130 17 100 1000
element FourNodeTetrahedron 300 60 17 130 61 1000
element FourNodeTetrahedron 301 17 60 97 127 1000
element FourNodeTetrahedron 302 17 97 60 16 1000
element FourNodeTetrahedron 303 56 97 60 127 1000
element FourNodeTetrahedron 304 12 125 52 56 1000
element FourNodeTetrahedron 305 12 94 52 8 1000
element FourNodeTetrahedron 306 52 94 12 56 1000
element FourNodeTetrahedron 307 101 20 60 16 1000
element FourNodeTetrahedron 308 100 60 20 16 1000
element FourNodeTetrahedron 309 78 82 113 38 1000
element FourNodeTetrahedron 310 78 113 82 143 1000
element FourNodeTetrahedron 311 36 113 82 38 1000
element FourNodeTetrahedron 312 36 82 113 143 1000
element FourNodeTetrahedron 313 28 73 109 139 1000
element FourNodeTetrahedron 314 28 109 73 29 1000
element FourNodeTetrahedron 315 77 109 73 139 1000
element FourNodeTetrahedron 316 77 73 109 29 1000
element FourNodeTetrahedron 317 122 49 10 5 1000
element FourNodeTetrahedron 318 122 10 49 54 1000
element FourNodeTetrahedron 319 123 10 49 5 1000
element FourNodeTetrahedron 320 123 49 10 54 1000
element FourNodeTetrahedron 321 66 23 132 67 1000
element FourNodeTetrahedron 322 66 132 23 102 1000
element FourNodeTetrahedron 323 19 132 23 67 1000
element FourNodeTetrahedron 324 19 23 132 102 1000
element FourNodeTetrahedron 325 1 47 88 2 1000
element FourNodeTetrahedron 326 1 88 47 118 1000
element FourNodeTetrahedron 327 44 88 47 2 1000
element FourNodeTetrahedron 328 44 47 88 118 1000
element FourNodeTetrahedron 329 42 116 82 38 1000
element FourNodeTetrahedron 330 82 116 42 86 1000
element FourNodeTetrahedron 331 82 117 42 38 1000
element FourNodeTetrahedron 332 42 117 82 86 1000
element FourNodeTetrahedron 333 45 4 119 89 1000
element FourNodeTetrahedron 334 45 119 4 48 1000
element FourNodeTetrahedron 335 5 119 4 89 1000
element FourNodeTetrahedron 336 5 4 119 48 1000
element FourNodeTetrahedron 337 145 84 36 80 1000
element FourNodeTetrahedron 338 146 36 84 80 1000
element FourNodeTetrahedron 339 146 84 36 40 1000
element FourNodeTetrahedron 340 74 75 30 138 1000
element FourNodeTetrahedron 341 74 30 75 151 1000
element FourNodeTetrahedron 342 31 75 30 151 1000
element FourNodeTetrahedron 343 32 34 78 113 1000
element FourNodeTetrahedron 344 78 34 32 154 1000
element FourNodeTetrahedron 345 32 76 78 154 1000
element FourNodeTetrahedron 346 22 20 66 149 1000
element FourNodeTetrahedron 347 64 20 66 134 1000
element FourNodeTetrahedron 348 64 66 20 149 1000
element FourNodeTetrahedron 349 71 70 26 138 1000
element FourNodeTetrahedron 350 26 70 71 152 1000
element FourNodeTetrahedron 351 71 27 26 152 1000
element FourNodeTetrahedron 352 70 104 66 22 1000
element FourNodeTetrahedron 353 70 66 104 134 1000
element FourNodeTetrahedron 354 20 66 104 22 1000
element FourNodeTetrahedron 355 20 104 66 134 1000
element FourNodeTetrahedron 356 108 27 75 31 1000
element FourNodeTetrahedron 357 75 30 108 31 1000
element FourNodeTetrahedron 358 108 30 75 138 1000
element FourNodeTetrahedron 359 20 103 68 133 1000
element FourNodeTetrahedron 360 20 68 103 24 1000
element FourNodeTetrahedron 361 25 68 103 133 1000
element FourNodeTetrahedron 362 25 103 68 24 1000
element FourNodeTetrahedron 363 130 60 20 100 1000
element FourNodeTetrahedron 364 20 60 130 64 1000
element FourNodeTetrahedron 365 20 65 130 100 1000
element FourNodeTetrahedron 366 130 65 20 64 1000
element FourNodeTetrahedron 367 36 143 32 76 1000
element FourNodeTetrahedron 368 36 32 143 113 1000
element FourNodeTetrahedron 369 78 32 143 76 1000
element FourNodeTetrahedron 370 78 143 32 113 1000
element FourNodeTetrahedron 371 12 95 52 125 1000
element FourNodeTetrahedron 372 12 52 95 8 1000
element FourNodeTetrahedron 373 10 52 95 125 1000
element FourNodeTetrahedron 374 10 95 52 8 1000
element FourNodeTetrahedron 375 36 115 84 145 1000
element FourNodeTetrahedron 376 36 84 115 40 1000
element FourNodeTetrahedron 377 41 84 115 145 1000
element FourNodeTetrahedron 378 41 115 84 40 1000
element FourNodeTetrahedron 379 149 131 20 64 1000
element FourNodeTetrahedron 380 149 20 131 101 1000
element FourNodeTetrahedron 381 60 20 131 64 1000
element FourNodeTetrahedron 382 60 131 20 101 1000
element FourNodeTetrahedron 383 97 60 12 56 1000
element FourNodeTetrahedron 384 97 12 60 16 1000
element FourNodeTetrahedron 385 98 12 60 56 1000
element FourNodeTetrahedron 386 98 60 12 16 1000
element FourNodeTetrahedron 387 26 71 108 27 1000
element FourNodeTetrahedron 388 26 108 71 138 1000
element FourNodeTetrahedron 389 75 108 71 27 1000
element FourNodeTetrahedron 390 75 71 108 138 1000
element FourNodeTetrahedron 391 138 70 30 74 1000
element FourNodeTetrahedron 392 138 30 70 26 1000
element FourNodeTetrahedron 393 107 30 70 74 1000
element FourNodeTetrahedron 394 107 70 30 26 1000
#
#
#
#
#------------------------------------------------------------------
# Initial conditions
#------------------------------------------------------------------
#
#    tag   DX   DY   RZ   MX   MY   MZ
fix 44 1 1 1
fix 45 1 1 1
fix 48 1 1 1
fix 50 1 1 1
fix 85 1 1 1
fix 84 1 1 1
fix 86 1 1 1
fix 87 1 1 1
fix 3 1 1 1
fix 0 1 1 1
fix 4 1 1 1
fix 6 1 1 1
fix 41 1 1 1
fix 40 1 1 1
fix 42 1 1 1
fix 43 1 1 1
#
#
#------------------------------------------------------------------
# Connectors
#------------------------------------------------------------------
#

#
#
#
#
# -----------------------------------------------------------------
# -----------------------------------------------------------------
# PROBLEM
# -----------------------------------------------------------------
# -----------------------------------------------------------------
#
##
#
# STEP OMA_5399505344
#
# Define the number of modes to compute
set numModes 6
#
# - Analysis Parameters
#   -------------------

# Compute eigenvalues (lambda) for the first 'numModes' modes
set eigenValues [eigen $numModes]
record

#
# - Output Results
#   --------------

set eigenFile [open "eigenvalues.out" "w"]

puts "------------------------------------------------------------------"
puts "Modal Analysis Results:"
puts "  Mode :   Lambda        Omega (rad/s)    Freq (Hz)   Period (s)"
puts "------------------------------------------------------------------"

for {set iMode 1} {$iMode <= $numModes} {incr iMode} {
    # lambda = eigenvalue
    set lambda   [lindex $eigenValues [expr $iMode-1]]
    set omega    [expr sqrt($lambda)]            ;# rad/s
    set freqHz   [expr $omega/(2.0*3.14159265359)]
    set Period   [expr 1.0/$freqHz]
    puts "   $iMode   :   $lambda   $omega   $freqHz  $Period"
    puts $eigenFile "$iMode $lambda $omega $freqHz $Period"
}
puts "Modal analysis results have been exported to eigen.out"
close $eigenFile
#
set nNodes 155

# Open a file for all eigenvectors
set shapeFile [open "eigenvectors.out" "w"]

for {set iMode 1} {$iMode <= $numModes} {incr iMode} {
    for {set iNode 0} {$iNode < $nNodes} {incr iNode} {
        puts $shapeFile [format "%d %d %s" $iMode $iNode [nodeEigenvector $iNode $iMode]]
    }
}
close $shapeFile


modalProperties -print -file "ModalReport.out" -unorm

#

