# ------------------------
# plate
# ------------------------
#
# None
#
#
# Author: None
# Description: None
# Date: 02/01/2025 16:50:34
# Generated by:
#   compas_fea2 v0.2.1
#   compas_fea2_opensees v0.1.0
#
#------------------------------------------------------------------
#------------------------------------------------------------------
# MODEL
#------------------------------------------------------------------
#------------------------------------------------------------------
#
##
model Basic -ndm 3 -ndf 3
#
#==================================================================
# Materials
#==================================================================
#
uniaxialMaterial Elastic 0 210000.0
nDMaterial ElasticIsotropic 1000 210000.0 0.2 7.800000000000002e-09
#
#==================================================================
# Sections
#==================================================================
#
section ElasticMembranePlateSection 0 210000.0 0.2 50 7.800000000000002e-09
#
#==================================================================
# Parts
#==================================================================
#
#
#------------------------------------------------------------------
# Part OP_5871020144
#------------------------------------------------------------------
model Basic -ndm 3 -ndf 6
#
# Nodes
#------------------------------------------------------------------
#
#    tag        X       Y       Z       mx      my      mz
node 42    900.000   2700.000      0.000
node 211   2850.000    150.000      0.000
node 127    150.000   1950.000      0.000
node 43    900.000   3000.000      0.000
node 212   2850.000    450.000      0.000
node 128    150.000   2250.000      0.000
node 44   1200.000      0.000      0.000
node 214   2850.000   1050.000      0.000
node 129    150.000   2550.000      0.000
node 45   1200.000    300.000      0.000
node 215   2850.000   1350.000      0.000
node 130    150.000   2850.000      0.000
node 46   1200.000    600.000      0.000
node 131    450.000    150.000      0.000
node 47   1200.000    900.000      0.000
node 216   2850.000   1650.000      0.000
node 132    450.000    450.000      0.000
node 48   1200.000   1200.000      0.000
node 217   2850.000   1950.000      0.000
node 136    450.000   1650.000      0.000
node 49   1200.000   1500.000      0.000
node 218   2850.000   2250.000      0.000
node 133    450.000    750.000      0.000
node 57   1500.000    600.000      0.000
node 219   2850.000   2550.000      0.000
node 134    450.000   1050.000      0.000
node 50   1200.000   1800.000      0.000
node 220   2850.000   2850.000      0.000
node 135    450.000   1350.000      0.000
node 51   1200.000   2100.000      0.000
node 10    300.000   1500.000      0.000
node 137    450.000   1950.000      0.000
node 52   1200.000   2400.000      0.000
node 138    450.000   2250.000      0.000
node 53   1200.000   2700.000      0.000
node 139    450.000   2550.000      0.000
node 54   1200.000   3000.000      0.000
node 140    450.000   2850.000      0.000
node 55   1500.000      0.000      0.000
node 141    750.000    150.000      0.000
node 56   1500.000    300.000      0.000
node 142    750.000    450.000      0.000
node 58   1500.000    900.000      0.000
node 146    750.000   1650.000      0.000
node 59   1500.000   1200.000      0.000
node 143    750.000    750.000      0.000
node 60   1500.000   1500.000      0.000
node 144    750.000   1050.000      0.000
node 68   1800.000    600.000      0.000
node 145    750.000   1350.000      0.000
node 61   1500.000   1800.000      0.000
node 147    750.000   1950.000      0.000
node 62   1500.000   2100.000      0.000
node 148    750.000   2250.000      0.000
node 63   1500.000   2400.000      0.000
node 149    750.000   2550.000      0.000
node 64   1500.000   2700.000      0.000
node 150    750.000   2850.000      0.000
node 65   1500.000   3000.000      0.000
node 2    300.000    300.000      0.000
node 151   1050.000    150.000      0.000
node 66   1800.000      0.000      0.000
node 152   1050.000    450.000      0.000
node 67   1800.000    300.000      0.000
node 153   1050.000    750.000      0.000
node 69   1800.000    900.000      0.000
node 154   1050.000   1050.000      0.000
node 70   1800.000   1200.000      0.000
node 155   1050.000   1350.000      0.000
node 71   1800.000   1500.000      0.000
node 163   1350.000    750.000      0.000
node 79   2100.000    600.000      0.000
node 156   1050.000   1650.000      0.000
node 72   1800.000   1800.000      0.000
node 157   1050.000   1950.000      0.000
node 73   1800.000   2100.000      0.000
node 158   1050.000   2250.000      0.000
node 74   1800.000   2400.000      0.000
node 159   1050.000   2550.000      0.000
node 75   1800.000   2700.000      0.000
node 160   1050.000   2850.000      0.000
node 76   1800.000   3000.000      0.000
node 161   1350.000    150.000      0.000
node 77   2100.000      0.000      0.000
node 162   1350.000    450.000      0.000
node 78   2100.000    300.000      0.000
node 164   1350.000   1050.000      0.000
node 209   2550.000   2550.000      0.000
node 4    300.000    600.000      0.000
node 80   2100.000    900.000      0.000
node 165   1350.000   1350.000      0.000
node 81   2100.000   1200.000      0.000
node 173   1650.000    750.000      0.000
node 82   2100.000   1500.000      0.000
node 3      0.000    300.000      0.000
node 166   1350.000   1650.000      0.000
node 90   2400.000    600.000      0.000
node 167   1350.000   1950.000      0.000
node 83   2100.000   1800.000      0.000
node 168   1350.000   2250.000      0.000
node 210   2550.000   2850.000      0.000
node 84   2100.000   2100.000      0.000
node 169   1350.000   2550.000      0.000
node 85   2100.000   2400.000      0.000
node 170   1350.000   2850.000      0.000
node 86   2100.000   2700.000      0.000
node 171   1650.000    150.000      0.000
node 87   2100.000   3000.000      0.000
node 172   1650.000    450.000      0.000
node 88   2400.000      0.000      0.000
node 174   1650.000   1050.000      0.000
node 89   2400.000    300.000      0.000
node 175   1650.000   1350.000      0.000
node 91   2400.000    900.000      0.000
node 5      0.000    600.000      0.000
node 183   1950.000    750.000      0.000
node 92   2400.000   1200.000      0.000
node 6    300.000    900.000      0.000
node 176   1650.000   1650.000      0.000
node 93   2400.000   1500.000      0.000
node 7      0.000    900.000      0.000
node 177   1650.000   1950.000      0.000
node 101   2700.000    600.000      0.000
node 8    300.000   1200.000      0.000
node 178   1650.000   2250.000      0.000
node 94   2400.000   1800.000      0.000
node 0      0.000      0.000      0.000
node 9      0.000   1200.000      0.000
node 179   1650.000   2550.000      0.000
node 95   2400.000   2100.000      0.000
node 11      0.000   1500.000      0.000
node 180   1650.000   2850.000      0.000
node 96   2400.000   2400.000      0.000
node 12    300.000   1800.000      0.000
node 181   1950.000    150.000      0.000
node 97   2400.000   2700.000      0.000
node 13      0.000   1800.000      0.000
node 1    300.000      0.000      0.000
node 182   1950.000    450.000      0.000
node 98   2400.000   3000.000      0.000
node 14    300.000   2100.000      0.000
node 184   1950.000   1050.000      0.000
node 99   2700.000      0.000      0.000
node 15      0.000   2100.000      0.000
node 185   1950.000   1350.000      0.000
node 100   2700.000    300.000      0.000
node 16    300.000   2400.000      0.000
node 193   2250.000    750.000      0.000
node 102   2700.000    900.000      0.000
node 17      0.000   2400.000      0.000
node 186   1950.000   1650.000      0.000
node 103   2700.000   1200.000      0.000
node 18    300.000   2700.000      0.000
node 187   1950.000   1950.000      0.000
node 104   2700.000   1500.000      0.000
node 19      0.000   2700.000      0.000
node 188   1950.000   2250.000      0.000
node 112   3000.000    600.000      0.000
node 20    300.000   3000.000      0.000
node 189   1950.000   2550.000      0.000
node 105   2700.000   1800.000      0.000
node 21      0.000   3000.000      0.000
node 190   1950.000   2850.000      0.000
node 106   2700.000   2100.000      0.000
node 22    600.000      0.000      0.000
node 191   2250.000    150.000      0.000
node 107   2700.000   2400.000      0.000
node 23    600.000    300.000      0.000
node 192   2250.000    450.000      0.000
node 108   2700.000   2700.000      0.000
node 28    600.000   1800.000      0.000
node 194   2250.000   1050.000      0.000
node 109   2700.000   3000.000      0.000
node 24    600.000    600.000      0.000
node 195   2250.000   1350.000      0.000
node 110   3000.000      0.000      0.000
node 25    600.000    900.000      0.000
node 203   2550.000    750.000      0.000
node 111   3000.000    300.000      0.000
node 26    600.000   1200.000      0.000
node 196   2250.000   1650.000      0.000
node 113   3000.000    900.000      0.000
node 27    600.000   1500.000      0.000
node 197   2250.000   1950.000      0.000
node 114   3000.000   1200.000      0.000
node 29    600.000   2100.000      0.000
node 198   2250.000   2250.000      0.000
node 115   3000.000   1500.000      0.000
node 30    600.000   2400.000      0.000
node 199   2250.000   2550.000      0.000
node 126    150.000   1650.000      0.000
node 31    600.000   2700.000      0.000
node 200   2250.000   2850.000      0.000
node 116   3000.000   1800.000      0.000
node 32    600.000   3000.000      0.000
node 201   2550.000    150.000      0.000
node 117   3000.000   2100.000      0.000
node 33    900.000      0.000      0.000
node 202   2550.000    450.000      0.000
node 118   3000.000   2400.000      0.000
node 34    900.000    300.000      0.000
node 204   2550.000   1050.000      0.000
node 119   3000.000   2700.000      0.000
node 39    900.000   1800.000      0.000
node 205   2550.000   1350.000      0.000
node 120   3000.000   3000.000      0.000
node 35    900.000    600.000      0.000
node 213   2850.000    750.000      0.000
node 121    150.000    150.000      0.000
node 36    900.000    900.000      0.000
node 206   2550.000   1650.000      0.000
node 122    150.000    450.000      0.000
node 37    900.000   1200.000      0.000
node 207   2550.000   1950.000      0.000
node 123    150.000    750.000      0.000
node 38    900.000   1500.000      0.000
node 208   2550.000   2250.000      0.000
node 124    150.000   1050.000      0.000
node 40    900.000   2100.000      0.000
node 125    150.000   1350.000      0.000
node 41    900.000   2400.000      0.000
#
# Elements
#------------------------------------------------------------------
#
element ShellDKGT 157 53 160 42 0
element ShellDKGT 242 67 181 78 0
element ShellDKGT 44 2 132 4 0
element ShellDKGT 129 46 153 35 0
element ShellDKGT 214 59 174 70 0
element ShellDKGT 101 38 146 27 0
element ShellDKGT 186 51 167 62 0
element ShellDKGT 356 97 210 98 0
element ShellDKGT 158 43 160 54 0
element ShellDKGT 243 78 181 77 0
element ShellDKGT 45 23 132 2 0
element ShellDKGT 130 36 153 47 0
element ShellDKGT 215 70 174 69 0
element ShellDKGT 102 28 146 39 0
element ShellDKGT 187 62 167 61 0
element ShellDKGT 357 108 210 97 0
element ShellDKGT 159 54 160 53 0
element ShellDKGT 244 67 182 68 0
element ShellDKGT 46 4 132 24 0
element ShellDKGT 131 47 153 46 0
element ShellDKGT 216 59 175 60 0
element ShellDKGT 103 39 146 38 0
element ShellDKGT 188 51 168 52 0
element ShellDKGT 358 98 210 109 0
element ShellDKGT 160 44 161 45 0
element ShellDKGT 245 78 182 67 0
element ShellDKGT 47 24 132 23 0
element ShellDKGT 132 36 154 37 0
element ShellDKGT 217 70 175 59 0
element ShellDKGT 104 28 147 29 0
element ShellDKGT 189 62 168 51 0
element ShellDKGT 359 109 210 108 0
element ShellDKGT 161 55 161 44 0
element ShellDKGT 246 68 182 79 0
element ShellDKGT 48 4 133 6 0
element ShellDKGT 133 47 154 36 0
element ShellDKGT 218 60 175 71 0
element ShellDKGT 105 39 147 28 0
element ShellDKGT 190 52 168 63 0
element ShellDKGT 360 99 211 100 0
element ShellDKGT 162 45 161 56 0
element ShellDKGT 247 79 182 78 0
element ShellDKGT 49 24 133 4 0
element ShellDKGT 134 37 154 48 0
element ShellDKGT 219 71 175 70 0
element ShellDKGT 106 29 147 40 0
element ShellDKGT 191 63 168 62 0
element ShellDKGT 361 110 211 99 0
element ShellDKGT 163 56 161 55 0
element ShellDKGT 248 68 183 69 0
element ShellDKGT 50 6 133 25 0
element ShellDKGT 135 48 154 47 0
element ShellDKGT 220 60 176 61 0
element ShellDKGT 107 40 147 39 0
element ShellDKGT 192 52 169 53 0
element ShellDKGT 362 100 211 111 0
element ShellDKGT 164 45 162 46 0
element ShellDKGT 249 79 183 68 0
element ShellDKGT 51 25 133 24 0
element ShellDKGT 136 37 155 38 0
element ShellDKGT 221 71 176 60 0
element ShellDKGT 108 29 148 30 0
element ShellDKGT 193 63 169 52 0
element ShellDKGT 363 111 211 110 0
element ShellDKGT 165 56 162 45 0
element ShellDKGT 250 69 183 80 0
element ShellDKGT 52 6 134 8 0
element ShellDKGT 137 48 155 37 0
element ShellDKGT 222 61 176 72 0
element ShellDKGT 109 40 148 29 0
element ShellDKGT 194 53 169 64 0
element ShellDKGT 364 100 212 101 0
element ShellDKGT 166 46 162 57 0
element ShellDKGT 251 80 183 79 0
element ShellDKGT 53 25 134 6 0
element ShellDKGT 138 38 155 49 0
element ShellDKGT 223 72 176 71 0
element ShellDKGT 110 30 148 41 0
element ShellDKGT 195 64 169 63 0
element ShellDKGT 365 111 212 100 0
element ShellDKGT 167 57 162 56 0
element ShellDKGT 252 69 184 70 0
element ShellDKGT 54 8 134 26 0
element ShellDKGT 139 49 155 48 0
element ShellDKGT 224 61 177 62 0
element ShellDKGT 111 41 148 40 0
element ShellDKGT 196 53 170 54 0
element ShellDKGT 366 101 212 112 0
element ShellDKGT 168 46 163 47 0
element ShellDKGT 253 80 184 69 0
element ShellDKGT 55 26 134 25 0
element ShellDKGT 140 38 156 39 0
element ShellDKGT 225 72 177 61 0
element ShellDKGT 112 30 149 31 0
element ShellDKGT 197 64 170 53 0
element ShellDKGT 367 112 212 111 0
element ShellDKGT 169 57 163 46 0
element ShellDKGT 254 70 184 81 0
element ShellDKGT 56 8 135 10 0
element ShellDKGT 141 49 156 38 0
element ShellDKGT 226 62 177 73 0
element ShellDKGT 113 41 149 30 0
element ShellDKGT 198 54 170 65 0
element ShellDKGT 368 101 213 102 0
element ShellDKGT 170 47 163 58 0
element ShellDKGT 255 81 184 80 0
element ShellDKGT 142 39 156 50 0
element ShellDKGT 227 73 177 72 0
element ShellDKGT 57 26 135 8 0
element ShellDKGT 114 31 149 42 0
element ShellDKGT 199 65 170 64 0
element ShellDKGT 369 112 213 101 0
element ShellDKGT 171 58 163 57 0
element ShellDKGT 256 70 185 71 0
element ShellDKGT 58 10 135 27 0
element ShellDKGT 143 50 156 49 0
element ShellDKGT 228 62 178 63 0
element ShellDKGT 115 42 149 41 0
element ShellDKGT 200 55 171 56 0
element ShellDKGT 370 102 213 113 0
element ShellDKGT 172 47 164 48 0
element ShellDKGT 257 81 185 70 0
element ShellDKGT 59 27 135 26 0
element ShellDKGT 144 39 157 40 0
element ShellDKGT 229 73 178 62 0
element ShellDKGT 116 31 150 32 0
element ShellDKGT 201 66 171 55 0
element ShellDKGT 371 113 213 112 0
element ShellDKGT 3 2 121 1 0
element ShellDKGT 173 58 164 47 0
element ShellDKGT 258 71 185 82 0
element ShellDKGT 60 10 136 12 0
element ShellDKGT 145 50 157 39 0
element ShellDKGT 230 63 178 74 0
element ShellDKGT 117 42 150 31 0
element ShellDKGT 202 56 171 67 0
element ShellDKGT 372 102 214 103 0
element ShellDKGT 4 2 122 3 0
element ShellDKGT 174 48 164 59 0
element ShellDKGT 259 82 185 81 0
element ShellDKGT 61 27 136 10 0
element ShellDKGT 146 40 157 51 0
element ShellDKGT 231 74 178 73 0
element ShellDKGT 355 108 209 107 0
element ShellDKGT 118 32 150 43 0
element ShellDKGT 203 67 171 66 0
element ShellDKGT 373 113 214 102 0
element ShellDKGT 5 4 122 2 0
element ShellDKGT 175 59 164 58 0
element ShellDKGT 260 71 186 72 0
element ShellDKGT 62 12 136 28 0
element ShellDKGT 147 51 157 50 0
element ShellDKGT 232 63 179 64 0
element ShellDKGT 119 43 150 42 0
element ShellDKGT 204 56 172 57 0
element ShellDKGT 374 103 214 114 0
element ShellDKGT 6 3 122 5 0
element ShellDKGT 176 48 165 49 0
element ShellDKGT 261 82 186 71 0
element ShellDKGT 63 28 136 27 0
element ShellDKGT 148 40 158 41 0
element ShellDKGT 233 74 179 63 0
element ShellDKGT 120 33 151 34 0
element ShellDKGT 205 67 172 56 0
element ShellDKGT 375 114 214 113 0
element ShellDKGT 7 5 122 4 0
element ShellDKGT 177 59 165 48 0
element ShellDKGT 262 72 186 83 0
element ShellDKGT 43 23 131 22 0
element ShellDKGT 64 12 137 14 0
element ShellDKGT 149 51 158 40 0
element ShellDKGT 234 64 179 75 0
element ShellDKGT 1 1 121 0 0
element ShellDKGT 121 44 151 33 0
element ShellDKGT 206 57 172 68 0
element ShellDKGT 376 103 215 104 0
element ShellDKGT 8 4 123 5 0
element ShellDKGT 178 49 165 60 0
element ShellDKGT 263 83 186 82 0
element ShellDKGT 65 28 137 12 0
element ShellDKGT 150 41 158 52 0
element ShellDKGT 235 75 179 74 0
element ShellDKGT 122 34 151 45 0
element ShellDKGT 207 68 172 67 0
element ShellDKGT 377 114 215 103 0
element ShellDKGT 9 6 123 4 0
element ShellDKGT 179 60 165 59 0
element ShellDKGT 264 72 187 73 0
element ShellDKGT 0 0 121 3 0
element ShellDKGT 66 14 137 29 0
element ShellDKGT 151 52 158 51 0
element ShellDKGT 236 64 180 65 0
element ShellDKGT 123 45 151 44 0
element ShellDKGT 208 57 173 58 0
element ShellDKGT 378 104 215 115 0
element ShellDKGT 10 5 123 7 0
element ShellDKGT 180 49 166 50 0
element ShellDKGT 265 83 187 72 0
element ShellDKGT 67 29 137 28 0
element ShellDKGT 152 41 159 42 0
element ShellDKGT 237 75 180 64 0
element ShellDKGT 124 34 152 35 0
element ShellDKGT 209 68 173 57 0
element ShellDKGT 379 115 215 114 0
element ShellDKGT 11 7 123 6 0
element ShellDKGT 181 60 166 49 0
element ShellDKGT 266 73 187 84 0
element ShellDKGT 68 14 138 16 0
element ShellDKGT 153 52 159 41 0
element ShellDKGT 238 65 180 76 0
element ShellDKGT 125 45 152 34 0
element ShellDKGT 210 58 173 69 0
element ShellDKGT 380 104 216 105 0
element ShellDKGT 12 6 124 7 0
element ShellDKGT 182 50 166 61 0
element ShellDKGT 267 84 187 83 0
element ShellDKGT 69 29 138 14 0
element ShellDKGT 154 42 159 53 0
element ShellDKGT 239 76 180 75 0
element ShellDKGT 126 35 152 46 0
element ShellDKGT 211 69 173 68 0
element ShellDKGT 381 115 216 104 0
element ShellDKGT 13 8 124 6 0
element ShellDKGT 183 61 166 60 0
element ShellDKGT 268 73 188 74 0
element ShellDKGT 70 16 138 30 0
element ShellDKGT 155 53 159 52 0
element ShellDKGT 240 66 181 67 0
element ShellDKGT 127 46 152 45 0
element ShellDKGT 212 58 174 59 0
element ShellDKGT 382 105 216 116 0
element ShellDKGT 14 7 124 9 0
element ShellDKGT 184 50 167 51 0
element ShellDKGT 269 84 188 73 0
element ShellDKGT 71 30 138 29 0
element ShellDKGT 156 42 160 43 0
element ShellDKGT 241 77 181 66 0
element ShellDKGT 185 61 167 50 0
element ShellDKGT 270 74 188 85 0
element ShellDKGT 15 9 124 8 0
element ShellDKGT 128 35 153 36 0
element ShellDKGT 213 69 174 58 0
element ShellDKGT 383 116 216 115 0
element ShellDKGT 72 16 139 18 0
element ShellDKGT 327 101 202 100 0
element ShellDKGT 299 93 195 92 0
element ShellDKGT 384 105 217 106 0
element ShellDKGT 16 8 125 9 0
element ShellDKGT 271 85 188 84 0
element ShellDKGT 73 30 139 16 0
element ShellDKGT 328 90 203 91 0
element ShellDKGT 300 82 196 83 0
element ShellDKGT 385 116 217 105 0
element ShellDKGT 17 10 125 8 0
element ShellDKGT 272 74 189 75 0
element ShellDKGT 74 18 139 31 0
element ShellDKGT 329 101 203 90 0
element ShellDKGT 301 93 196 82 0
element ShellDKGT 386 106 217 117 0
element ShellDKGT 18 9 125 11 0
element ShellDKGT 273 85 189 74 0
element ShellDKGT 75 31 139 30 0
element ShellDKGT 330 91 203 102 0
element ShellDKGT 302 83 196 94 0
element ShellDKGT 387 117 217 116 0
element ShellDKGT 19 11 125 10 0
element ShellDKGT 274 75 189 86 0
element ShellDKGT 76 18 140 20 0
element ShellDKGT 331 102 203 101 0
element ShellDKGT 303 94 196 93 0
element ShellDKGT 388 106 218 107 0
element ShellDKGT 20 10 126 11 0
element ShellDKGT 275 86 189 85 0
element ShellDKGT 77 31 140 18 0
element ShellDKGT 332 91 204 92 0
element ShellDKGT 304 83 197 84 0
element ShellDKGT 389 117 218 106 0
element ShellDKGT 21 12 126 10 0
element ShellDKGT 276 75 190 76 0
element ShellDKGT 78 20 140 32 0
element ShellDKGT 333 102 204 91 0
element ShellDKGT 305 94 197 83 0
element ShellDKGT 390 107 218 118 0
element ShellDKGT 22 11 126 13 0
element ShellDKGT 277 86 190 75 0
element ShellDKGT 79 32 140 31 0
element ShellDKGT 334 92 204 103 0
element ShellDKGT 306 84 197 95 0
element ShellDKGT 391 118 218 117 0
element ShellDKGT 23 13 126 12 0
element ShellDKGT 278 76 190 87 0
element ShellDKGT 80 34 141 33 0
element ShellDKGT 335 103 204 102 0
element ShellDKGT 307 95 197 94 0
element ShellDKGT 392 107 219 108 0
element ShellDKGT 24 12 127 13 0
element ShellDKGT 279 87 190 86 0
element ShellDKGT 81 33 141 22 0
element ShellDKGT 336 92 205 93 0
element ShellDKGT 308 84 198 85 0
element ShellDKGT 393 118 219 107 0
element ShellDKGT 25 14 127 12 0
element ShellDKGT 280 89 191 88 0
element ShellDKGT 82 23 141 34 0
element ShellDKGT 337 103 205 92 0
element ShellDKGT 309 95 198 84 0
element ShellDKGT 394 108 219 119 0
element ShellDKGT 2 3 121 2 0
element ShellDKGT 26 13 127 15 0
element ShellDKGT 281 77 191 78 0
element ShellDKGT 83 22 141 23 0
element ShellDKGT 338 93 205 104 0
element ShellDKGT 310 85 198 96 0
element ShellDKGT 395 119 219 118 0
element ShellDKGT 27 15 127 14 0
element ShellDKGT 282 88 191 77 0
element ShellDKGT 84 23 142 24 0
element ShellDKGT 339 104 205 103 0
element ShellDKGT 311 96 198 95 0
element ShellDKGT 396 108 220 109 0
element ShellDKGT 28 14 128 15 0
element ShellDKGT 283 78 191 89 0
element ShellDKGT 85 34 142 23 0
element ShellDKGT 340 93 206 94 0
element ShellDKGT 312 85 199 86 0
element ShellDKGT 397 119 220 108 0
element ShellDKGT 29 16 128 14 0
element ShellDKGT 284 78 192 79 0
element ShellDKGT 86 24 142 35 0
element ShellDKGT 341 104 206 93 0
element ShellDKGT 313 96 199 85 0
element ShellDKGT 398 109 220 120 0
element ShellDKGT 30 15 128 17 0
element ShellDKGT 285 89 192 78 0
element ShellDKGT 87 35 142 34 0
element ShellDKGT 342 94 206 105 0
element ShellDKGT 314 86 199 97 0
element ShellDKGT 399 120 220 119 0
element ShellDKGT 31 17 128 16 0
element ShellDKGT 286 79 192 90 0
element ShellDKGT 88 24 143 25 0
element ShellDKGT 343 105 206 104 0
element ShellDKGT 315 97 199 96 0
element ShellDKGT 32 16 129 17 0
element ShellDKGT 287 90 192 89 0
element ShellDKGT 89 35 143 24 0
element ShellDKGT 344 94 207 95 0
element ShellDKGT 316 86 200 87 0
element ShellDKGT 33 18 129 16 0
element ShellDKGT 288 79 193 80 0
element ShellDKGT 90 25 143 36 0
element ShellDKGT 345 105 207 94 0
element ShellDKGT 317 97 200 86 0
element ShellDKGT 34 17 129 19 0
element ShellDKGT 289 90 193 79 0
element ShellDKGT 91 36 143 35 0
element ShellDKGT 346 95 207 106 0
element ShellDKGT 318 87 200 98 0
element ShellDKGT 35 19 129 18 0
element ShellDKGT 290 80 193 91 0
element ShellDKGT 92 25 144 26 0
element ShellDKGT 347 106 207 105 0
element ShellDKGT 319 98 200 97 0
element ShellDKGT 36 18 130 19 0
element ShellDKGT 291 91 193 90 0
element ShellDKGT 93 36 144 25 0
element ShellDKGT 348 95 208 96 0
element ShellDKGT 320 88 201 89 0
element ShellDKGT 37 20 130 18 0
element ShellDKGT 292 80 194 81 0
element ShellDKGT 94 26 144 37 0
element ShellDKGT 349 106 208 95 0
element ShellDKGT 321 99 201 88 0
element ShellDKGT 38 19 130 21 0
element ShellDKGT 293 91 194 80 0
element ShellDKGT 95 37 144 36 0
element ShellDKGT 350 96 208 107 0
element ShellDKGT 322 89 201 100 0
element ShellDKGT 39 21 130 20 0
element ShellDKGT 294 81 194 92 0
element ShellDKGT 96 26 145 27 0
element ShellDKGT 351 107 208 106 0
element ShellDKGT 323 100 201 99 0
element ShellDKGT 40 1 131 2 0
element ShellDKGT 295 92 194 91 0
element ShellDKGT 97 37 145 26 0
element ShellDKGT 352 96 209 97 0
element ShellDKGT 324 89 202 90 0
element ShellDKGT 41 22 131 1 0
element ShellDKGT 296 81 195 82 0
element ShellDKGT 98 27 145 38 0
element ShellDKGT 353 107 209 96 0
element ShellDKGT 325 100 202 89 0
element ShellDKGT 42 2 131 23 0
element ShellDKGT 297 92 195 81 0
element ShellDKGT 99 38 145 37 0
element ShellDKGT 354 97 209 108 0
element ShellDKGT 326 90 202 101 0
element ShellDKGT 100 27 146 28 0
element ShellDKGT 298 82 195 93 0
#
#
#
#
#------------------------------------------------------------------
# Initial conditions
#------------------------------------------------------------------
#
#    tag   DX   DY   RZ   MX   MY   MZ
fix 0 1 1 1 0 0 0
fix 21 1 1 1 0 0 0
fix 110 1 1 1 0 0 0
fix 120 1 1 1 0 0 0
#
#
#------------------------------------------------------------------
# Connectors
#------------------------------------------------------------------
#

#
#
#
#
# -----------------------------------------------------------------
# -----------------------------------------------------------------
# PROBLEM
# -----------------------------------------------------------------
# -----------------------------------------------------------------
#
##
#
# STEP OSS_5917665728
#
#
timeSeries Constant 0 -factor 1.0
#
# - Displacements
#   -------------
#
#
# - Loads
#   -----
pattern Plain 0 0 -fact 1 {
	load 48 0.0 0.0 -11229.554 0.0 0.0 0.0
	load 53 0.0 0.0 -229.55400000000003 0.0 0.0 0.0
	load 160 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 42 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 67 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 181 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 78 0.0 0.0 -229.55399999999986 0.0 0.0 0.0
	load 2 0.0 0.0 -229.55400000000023 0.0 0.0 0.0
	load 132 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 4 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 46 0.0 0.0 -229.55400000000014 0.0 0.0 0.0
	load 153 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 35 0.0 0.0 -229.55399999999992 0.0 0.0 0.0
	load 59 0.0 0.0 -229.5540000000002 0.0 0.0 0.0
	load 174 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 70 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 38 0.0 0.0 -229.55399999999997 0.0 0.0 0.0
	load 146 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 27 0.0 0.0 -229.5539999999999 0.0 0.0 0.0
	load 51 0.0 0.0 -229.55399999999997 0.0 0.0 0.0
	load 167 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 62 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 97 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 210 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 98 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 43 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 54 0.0 0.0 -114.77699999999994 0.0 0.0 0.0
	load 77 0.0 0.0 -114.77699999999983 0.0 0.0 0.0
	load 23 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 36 0.0 0.0 -229.55399999999986 0.0 0.0 0.0
	load 47 0.0 0.0 -229.55399999999995 0.0 0.0 0.0
	load 69 0.0 0.0 -229.5539999999999 0.0 0.0 0.0
	load 28 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 39 0.0 0.0 -229.55400000000017 0.0 0.0 0.0
	load 61 0.0 0.0 -229.5540000000003 0.0 0.0 0.0
	load 108 0.0 0.0 -229.55399999999997 0.0 0.0 0.0
	load 182 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 68 0.0 0.0 -229.55400000000012 0.0 0.0 0.0
	load 24 0.0 0.0 -229.55399999999995 0.0 0.0 0.0
	load 175 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 60 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 168 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 52 0.0 0.0 -229.55399999999986 0.0 0.0 0.0
	load 109 0.0 0.0 -114.77700000000011 0.0 0.0 0.0
	load 44 0.0 0.0 -114.77699999999999 0.0 0.0 0.0
	load 161 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 45 0.0 0.0 -229.55400000000014 0.0 0.0 0.0
	load 154 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 37 0.0 0.0 -229.55400000000023 0.0 0.0 0.0
	load 147 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 29 0.0 0.0 -229.55400000000003 0.0 0.0 0.0
	load 55 0.0 0.0 -114.777 0.0 0.0 0.0
	load 79 0.0 0.0 -229.554 0.0 0.0 0.0
	load 133 0.0 0.0 -114.77700000000002 0.0 0.0 0.0
	load 6 0.0 0.0 -229.55399999999995 0.0 0.0 0.0
	load 71 0.0 0.0 -229.55400000000012 0.0 0.0 0.0
	load 63 0.0 0.0 -229.55400000000026 0.0 0.0 0.0
	load 99 0.0 0.0 -114.77699999999996 0.0 0.0 0.0
	load 211 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 100 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 56 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 40 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 110 0.0 0.0 -57.38849999999998 0.0 0.0 0.0
	load 183 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 25 0.0 0.0 -229.55399999999983 0.0 0.0 0.0
	load 176 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 169 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 111 0.0 0.0 -114.77700000000007 0.0 0.0 0.0
	load 162 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 155 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 148 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 30 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 80 0.0 0.0 -229.55399999999972 0.0 0.0 0.0
	load 134 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 8 0.0 0.0 -229.55400000000026 0.0 0.0 0.0
	load 72 0.0 0.0 -229.55400000000003 0.0 0.0 0.0
	load 64 0.0 0.0 -229.55400000000026 0.0 0.0 0.0
	load 212 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 101 0.0 0.0 -229.55399999999992 0.0 0.0 0.0
	load 57 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 49 0.0 0.0 -229.5539999999999 0.0 0.0 0.0
	load 41 0.0 0.0 -229.55399999999992 0.0 0.0 0.0
	load 184 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 26 0.0 0.0 -229.55400000000017 0.0 0.0 0.0
	load 177 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 170 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 112 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 163 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 156 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 149 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 31 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 81 0.0 0.0 -229.55400000000023 0.0 0.0 0.0
	load 135 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 10 0.0 0.0 -229.5540000000001 0.0 0.0 0.0
	load 73 0.0 0.0 -229.55400000000012 0.0 0.0 0.0
	load 65 0.0 0.0 -114.77700000000013 0.0 0.0 0.0
	load 213 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 102 0.0 0.0 -229.55399999999977 0.0 0.0 0.0
	load 58 0.0 0.0 -229.5539999999999 0.0 0.0 0.0
	load 50 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 185 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 178 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 171 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 113 0.0 0.0 -114.77699999999986 0.0 0.0 0.0
	load 164 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 157 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 150 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 32 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 66 0.0 0.0 -114.77699999999996 0.0 0.0 0.0
	load 121 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 1 0.0 0.0 -114.77700000000009 0.0 0.0 0.0
	load 82 0.0 0.0 -229.55399999999995 0.0 0.0 0.0
	load 136 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 12 0.0 0.0 -229.5540000000003 0.0 0.0 0.0
	load 74 0.0 0.0 -229.554 0.0 0.0 0.0
	load 214 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 103 0.0 0.0 -229.55400000000031 0.0 0.0 0.0
	load 122 0.0 0.0 -114.77700000000002 0.0 0.0 0.0
	load 3 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 209 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 107 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 186 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 179 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 172 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 114 0.0 0.0 -114.77700000000016 0.0 0.0 0.0
	load 5 0.0 0.0 -114.77700000000013 0.0 0.0 0.0
	load 165 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 158 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 33 0.0 0.0 -114.77699999999999 0.0 0.0 0.0
	load 151 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 34 0.0 0.0 -229.55400000000017 0.0 0.0 0.0
	load 83 0.0 0.0 -229.55399999999975 0.0 0.0 0.0
	load 131 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 22 0.0 0.0 -114.77699999999996 0.0 0.0 0.0
	load 137 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 14 0.0 0.0 -229.55400000000014 0.0 0.0 0.0
	load 75 0.0 0.0 -229.55399999999995 0.0 0.0 0.0
	load 0 0.0 0.0 -57.38850000000001 0.0 0.0 0.0
	load 215 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 104 0.0 0.0 -229.554 0.0 0.0 0.0
	load 123 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 187 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 180 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 173 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 115 0.0 0.0 -114.77700000000009 0.0 0.0 0.0
	load 7 0.0 0.0 -114.77699999999993 0.0 0.0 0.0
	load 166 0.0 0.0 -114.77700000000002 0.0 0.0 0.0
	load 159 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 152 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 84 0.0 0.0 -229.55400000000006 0.0 0.0 0.0
	load 138 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 16 0.0 0.0 -229.55400000000014 0.0 0.0 0.0
	load 76 0.0 0.0 -114.77700000000011 0.0 0.0 0.0
	load 216 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 105 0.0 0.0 -229.55400000000017 0.0 0.0 0.0
	load 124 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 188 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 116 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 9 0.0 0.0 -114.77699999999996 0.0 0.0 0.0
	load 85 0.0 0.0 -229.55399999999995 0.0 0.0 0.0
	load 139 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 18 0.0 0.0 -229.55400000000017 0.0 0.0 0.0
	load 202 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 93 0.0 0.0 -229.55400000000014 0.0 0.0 0.0
	load 195 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 92 0.0 0.0 -229.5540000000003 0.0 0.0 0.0
	load 217 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 106 0.0 0.0 -229.55399999999997 0.0 0.0 0.0
	load 125 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 90 0.0 0.0 -229.55400000000037 0.0 0.0 0.0
	load 203 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 91 0.0 0.0 -229.55399999999977 0.0 0.0 0.0
	load 196 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 189 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 117 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 11 0.0 0.0 -114.77699999999992 0.0 0.0 0.0
	load 94 0.0 0.0 -229.55400000000046 0.0 0.0 0.0
	load 86 0.0 0.0 -229.55400000000003 0.0 0.0 0.0
	load 140 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 20 0.0 0.0 -114.77700000000007 0.0 0.0 0.0
	load 218 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 126 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 204 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 197 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 190 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 118 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 13 0.0 0.0 -114.77700000000009 0.0 0.0 0.0
	load 95 0.0 0.0 -229.55400000000037 0.0 0.0 0.0
	load 87 0.0 0.0 -114.77700000000013 0.0 0.0 0.0
	load 141 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 219 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 127 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 205 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 198 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 89 0.0 0.0 -229.5540000000006 0.0 0.0 0.0
	load 191 0.0 0.0 -114.77700000000002 0.0 0.0 0.0
	load 88 0.0 0.0 -114.77700000000013 0.0 0.0 0.0
	load 119 0.0 0.0 -114.77699999999994 0.0 0.0 0.0
	load 15 0.0 0.0 -114.77699999999999 0.0 0.0 0.0
	load 96 0.0 0.0 -229.55400000000026 0.0 0.0 0.0
	load 142 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 220 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 128 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 206 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 199 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 192 0.0 0.0 -114.77700000000002 0.0 0.0 0.0
	load 120 0.0 0.0 -57.38850000000011 0.0 0.0 0.0
	load 17 0.0 0.0 -114.77699999999999 0.0 0.0 0.0
	load 143 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 129 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 207 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 200 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 193 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 19 0.0 0.0 -114.77699999999994 0.0 0.0 0.0
	load 144 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 130 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 208 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 201 0.0 0.0 -114.77700000000004 0.0 0.0 0.0
	load 194 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
	load 21 0.0 0.0 -57.388499999999965 0.0 0.0 0.0
	load 145 0.0 0.0 -114.77700000000003 0.0 0.0 0.0
}
#
# - Predefined Fields
#   -----------------
#
#
# - Output Requests
#   ---------------
#
#
recorder Node -file u.out -time -nodeRange 0 220 -dof 1 2 3 disp
recorder Node -file rf.out -time -nodeRange 0 220 -dof 1 2 3 reaction
recorder Element -file s2d.out -time -eleRange 0 399 -dof 1 2 3 4 5 6 stresses
recorder Element -file sf.out -time -eleRange 0 399 -dof 1 2 3 4 5 6 force
#
# - Analysis Parameters
#   -------------------
#
constraints Transformation
numberer RCM
system BandGeneral
test NormDispIncr 1e-06 10
algorithm Newton
integrator LoadControl 1

analysis Static

analyze 1
loadConst -time 0.0

